import mongoose, { Schema, models } from "mongoose";

const XentaSchema = new Schema({
    id: { type: String },
    datosempresas_id: { type: String },
    borradoresdearriendo_id: { type: String, default: "0" },
    borradoresdetraslado_id: { type: String, default: null },
    borradoresdetraslado: { type: String, default: null },
    arriendo: { type: String, default: "no" },
    ventarapida: { type: String, default: "No" },
    codigo: { type: String },
    vendedor: { type: String },
    usuario: { type: String, default: null },
    ip: { type: String, default: null },
    tipo_doc: { type: String, default: null },
    hora: { type: String },
    fecha: { type: Date },
    clientes_id: { type: String },
    rut: { type: String },
    nombre: { type: String },
    email: { type: String, default: null },
    telefono: { type: String, default: null },
    celular: { type: String, default: null },
    direccion: { type: String },
    ciudad: { type: String },
    comunas_id: { type: String },
    giro: { type: String },
    detallecot: { type: String, default: null },
    permanente: { type: String, default: null },
    titulo: { type: String, default: null },
    comentario: { type: String, default: null },
    estado: { type: String },
    valor_neto: { type: Number },
    valor_exento: { type: Number, default: 0 },
    valor_iva: { type: Number },
    valor_bruto: { type: Number },
    valor_total: { type: Number },
    numdoc: { type: String },
    num_vale: { type: String, default: null },
    documentotributario_id: { type: String },
    detalleguiadespacho: { type: String, default: "0" },
    sucursaldestino: { type: String },
    estado_guia: { type: String, default: null },
    tipoanterior: { type: String, default: null },
    tasaimp: { type: Number },
    anterior: { type: String, default: null },
    tipo_nota_guia: { type: String, default: null },
    fecha_anterior: { type: Date, default: null },
    raz_ref: { type: String, default: null },
    formapago_id: { type: String },
    ot: { type: String, default: "No" },
    control_envase: { type: String, default: null },
    motivo: { type: String, default: null },
    otoc: { type: String, default: null },
    otocdate: { type: Date, default: null },
    hes: { type: String, default: null },
    trackid: { type: String, default: null },
    aceptado: { type: Boolean, default: false },
    rechazado: { type: Boolean, default: false },
    reparos: { type: Boolean, default: false },
    perdido: { type: String, default: null },
    sucursales_id: { type: String },
    recibe: { type: String, default: null },
    conductor: { type: String, default: null },
    transportista: { type: String, default: null },
    patente: { type: String, default: null },
    proveedor: { type: String, default: null },
    porcobrar: { type: String, default: "no" },
    activa: { type: String, default: "si" },
    agrupada: { type: String, default: null },
    medio_despacho: { type: String },
    numerotraslado: { type: String, default: "" },
    origen: { type: String, default: null },
    referenciados: { type: String, default: "no" },
    recibido: { type: String, default: null },
    fecha_acuse: { type: Date, default: null },
    estado_dte: { type: String, default: null },
    cant_consultas_sii: { type: Number, default: 0 },
    cant_reenvios_sii: { type: Number, default: null },
    user_delete: { type: String, default: null },
    ejecutivo_id: { type: String, default: null },
    porcentaje_comision: { type: Number, default: null },
    valor_comision: { type: Number, default: null },
    notificaciones: { type: String, default: null },
    encola: { type: String, default: "no" },
    id_comcliusu: { type: String, default: null },
    por_comcliusu: { type: String, default: null },
    monto_comcliusu: { type: Number, default: null },
    centrodecosto_id: { type: String, default: null },
    deleted_at: { type: Date, default: null },
    created_at: { type: Date },
    updated_at: { type: Date }
});

const Xenta = models.Xenta || mongoose.model("Xenta", XentaSchema);
export default Xenta;